- CMakeLists.txt
- cmake/braft.cmake
- cmake/brpc.cmake
- cmake/gflags.cmake
- cmake/protobuf.cmake
- cmake/rocksdb.cmake
The option DOWNLOAD_EXTRACT_TIMESTAMP cannot work correctly on old cmake version.
Add cmake version check for policy CMP0135 to fix this problem.
Signed-off-by: Ketor <d.ketor@gmail.com>
> [cmake] Fix cmake error on old cmake version.

- cmake/brpc.cmake
Update brpc.cmake to support internal openssl version.
Bump up OpenSSL version to 3.0.8.
> [cmake] Bump up OpenSSL version to 3.0.8.

- src/coordinator/coordinator_control.cc
[cmake] Fix compile erro on CentOS 7.
FILE.h is not needed in dingo-poc.
> [cmake] Fix compile erro on CentOS 7.

- src/coordinator/coordinator_control.cc
The formal code wrongly generate MetaIncrement, casuse fatal exit.
> [meta] Fix drop table bug.

- conf/coordinator.template.yaml
- conf/coordinator.yaml
- conf/store.template.yaml
- conf/store.yaml
- proto/common.proto
- proto/coordinator.proto
- proto/coordinator_internal.proto
- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/meta_client.cc
- src/common/helper.cc
- src/common/helper.h
- src/common/meta_control.h
- src/coordinator/coordinator_closure.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/meta/coordinator_meta_manager.cc
- src/meta/coordinator_meta_manager.h
- src/meta/store_meta_manager.cc
- src/raft/store_state_machine.cc
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/meta_service.cc
- src/server/meta_service.h
- src/server/server.cc
- src/server/server.h
- src/store/heartbeat.cc
- src/store/store_control.cc
- src/store/store_control.h
[feat][coordinator]  Add ExecutorMap, add keyring validate for executor
and store.
During develop stage, we can use a super password keyring
TO_BE_CONTINUED to bypass keyring check.
[fix][common] Fix a char compare with integer bug in Helper::Increment.
[feat][coordinator] Add CreateTableId rpc call for SDK.
SDK needs get table_id to generate the range of partitions, so SDK can
now call CreateTableId to get a legal table_id, and then use this
table_id to create table.
[feat][store] Trigger immediately heartbeat after on_leader_start.
Now create table will finish in less than 5 seconds.
> [feat][coordinator&store] Add ExecutorMap & CreateTableId,  Speed up create_table

- src/common/helper.cc
Gcc version < 12 do not have bits/chrono.h, use <chrono> instead.
> [fix][common] Fix chrono headers caused compiling error.

- java/dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
- java/dingo-mysql-init/src/main/resources/table-information-global_variables.json
- java/dingo-mysql-init/src/main/resources/table-mysql-db.json
- java/dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json
- java/dingo-mysql-init/src/main/resources/table-mysql-user.json
1. 初始化元数据表时，varchar类型的scale不能为0，因为calcite验证会出错
> [fix][dingo-mysql-init] Fix init meta table bug: varchar -> scale:0

- CMakeLists.txt
- proto/coordinator.proto
- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/coordinator_client_function_incr.cc
- src/client/coordinator_client_function_meta.cc
- src/common/meta_control.h
- src/coordinator/auto_increment_control.cc
- src/coordinator/auto_increment_control.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_interaction.cc
- src/coordinator/coordinator_interaction.h
- src/server/coordinator_service.cc
- src/server/meta_service.cc
- src/server/meta_service.h
- src/server/server.cc
- src/server/server.h
[refactor][coordinator] Use coordinator interaction to refactor coordinator_client.
Now we need to get a coor_list file to use coordinator_client.
The "coor_list" file can be found in coordinator/store 's conf directory after using deploy.sh to get a new cluster.
Then we can use like this:
`./dingodb_client_coordinator --url=file://./coor_list --method=GetStoreMap`
If you just place coor_list in pwd, you can omit the --url parameter, like this:
`./dingodb_client_coordinator --method=GetStoreMap`
The client will default use file://./coor_list as the --url parameter value.
If you need to call raft control functions (RaftAddPeer) or node service functions( ChangeLogLevel),  you still need to pass --addr=host:port  which is the node you want to access, like this:
`./dingodb_client_coordinator …
> [refactor][coordinator] Refactor coordinator client

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/cluster/ClusterServiceClient.java
1. get executor map filter by normal
> [fix][dingo-sdk] Fix bug: filter executor, keep only normal

- proto/raft.proto
- proto/store.proto
- src/client/store_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/engine/raw_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/write_data.h
- src/handler/handler.h
- src/handler/raft_handler.cc
- src/handler/raft_handler.h
- src/server/store_service.cc
- src/server/store_service.h
- test/test_rocks_engine.cc
Batch implementation comparisons and settings.
There are three layers of semantics:
1. If the key does not exist, set kv.
2. The key exists and can be deleted.
3. The key exists to update the value.
Not available internally, only for RPC use.
>     [feat][store] Add CompareAndSet.

- src/vector/vector_index_flat.cc
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- test/test_vector_index_hnsw.cc
[fix][index] Fix Parallel HNSW upsert when both nlinks and elements is very small.
The hnsw index update neighbour's links in parallel may cause some points never be iterated during vector search.
This corner case only ocurs when nlinks is very small (nlinks < 8) and the elements in the hnsw index is also very very few (elements < 64).
> [fix][index] Fix Parallel HNSW upsert when both nlinks and elements is very small.

- src/vector/vector_reader.cc
- src/vector/vector_reader.h
[fix][index] Use accurate vector count for VectorGetRegionMetrics.
[fix][index] Fix VectorScanQuery and GetBorderId for prev scan.
> [fix][index] Fix VectorScanQuery and GetBorderId for prev scan.

- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
[fix][coordinator] SplitRegion add STORE_REGION_CHECK to prevent confilct CreateRegion and SplitRegion.
Improve send store_operation performance for not delete region operations.
> [fix][coordinator] SplitRegion add STORE_REGION_CHECK to prevent

- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/metrics/dingo_bvar.h
[fix][coordinator] Add AddCheckSplitResultTask before clean split task list to make split more serializable.
[fix][common] Fix DingoMultiDimension coredump in destruct function.
[fix][coordinator] Fix follower can't update region map.
> [fix] fix follower update regionmap

- conf/index.template.yaml
- src/engine/storage.cc
- src/engine/storage.h
- src/server/index_service.cc
VectorAdd, VectorSearch and VectorDelete use parallel threads or omp to speed up the vector index operations, and the batch op also may depelete the brpc bthreads for rpc processing when there is many many index regions in a index process. So we use wq to limit the concurrent threads count of these operations and use isolated bthreads to protect the rpc processing to proceed.
> [feat][index] Use wq to do vector add, search and delete.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/cluster/ClusterServiceClient.java
Correct the position of regionType and regionState in the returned region
> [fix][dingo-sdk] Correct the position of regionType and regionState in the returned region

- proto/coordinator.proto
- proto/coordinator_internal.proto
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
[fix][coordinator] Fix coordinator cannot re-route region_cmd when raft not leader is detected.
> [fix][coordinator] Fix coordinator cannot re-route region_cmd when raft

- proto/store.proto
- src/client/store_client_function_txn.cc
- src/engine/engine.h
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/txn_engine_helper.cc
- src/engine/txn_engine_helper.h
- src/server/index_service.cc
- src/server/store_service.cc
[feat][store] Implement min_commit_ts logic to reduce read-write conflict.
The min_commit_ts works in TxnGet, TxnScan, TxnCheckTxnStatus and TxnCommit. It is used to reduct the read-write conflict.
> [feat][store] Implement min_commit_ts logic to reduce read-write

- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
[feat][index] Remove range search flat with param patch. Because the  faiss library already supports it.
> [feat][index] Remove range search flat with param patch. Because the  faiss library already supports it.

- src/server/index_service.cc
If the vector id is not exists, store do wrong value check for kv returned from txn_engine_helper and return empty value of vector kv value to sdk.
> [fix][index] Fix TxnGet for vector.

- CMakeLists.txt
- src/common/runnable.cc
- src/server/region_service.cc
- src/store/region_controller.cc
Fix region_service coredump when a region is index by not a vector region.
Fix brpc hang up when deleting many regions. Because DeleteRange in BDB is very heavy, to many execq do delete_range will cause dead_lock and all brpc threads cpu 100%.
> [fix] Fix region_service coredump.

- src/vector/vector_index_bruteforce.cc
[fix][index] Fixed error when calling VectorGetRegionMetrics rpc when index is bruteforce.
> [fix][index] Fixed error when calling VectorGetRegionMetrics rpc when index is bruteforce.

- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/vector/vector_index_diskann.cc
- test/unit_test/vector/test_diskann_item_ann.cc
[fix][index] Fixed the issue that DiskANN timed out when importing large data.
The reason was that the protocol ByteSizeLong api executed too slowly.
[feat][client] Enhanced VectorImport to allow passing in files.
Currently only supports sift fvec format.
[test][index] Add DiskANN sift benchmark.
> [feat][index] Dealing with DiskANN related issues.

- src/client/store_client_function.cc
[fix][client] Fixed a crash when the original vector does not exist during vector query.
> [fix][client] Fixed a crash when the original vector does not exist during vector query.

- src/diskann/diskann_core.cc
- src/diskann/diskann_core.h
- src/diskann/diskann_item.cc
- src/diskann/diskann_item.h
- src/vector/vector_index_diskann.cc
- src/vector/vector_index_diskann.h
[fix][index] Fix DINGODB-2346 issue. Fixed the crash problem when
calling try load atomic variables in index process.
The reason is that asynchronous thread is used to access the destructor
object members. Change to shared_ptr mode for passing.
Other similar problems have also been fixed.
[fix][index] Fixed the issue that the next time you start load, the wrong metric type
is used.
[fix][index] Fixed the problem that the reset operation cannot be called
when build failed or load failed.
> [fix][index] Fix Diskann  Related issue.

- src/common/constant.h
- src/diskann/diskann_item.cc
- src/diskann/diskann_item.h
- src/diskann/diskann_service_handle.cc
- src/diskann/diskann_service_handle.h
- src/server/diskann_service.cc
- src/server/diskann_service.h
- src/vector/vector_index_diskann.cc
- src/vector/vector_index_diskann.h
[fix][index] Fix the bug that diskann build pq data exceeds 2^31 squares. And optimize the error reporting time. It is only found on the index side.
> [fix][index] Fix the bug that diskann build pq data exceeds 2^31 squares. And optimize the error reporting time. It is only found on the index side.

- src/server/index_service.cc
[feat][index] Add DiskAnn vector type
mysql> CREATE TABLE test (        id bigint not null,        feature float array not null,        feature_id bigint not null,        diskann_id bigint not null,        description varchar not null,        category varchar not null,        rating bigint not null,        text_id bigint not null,        INDEX text_index TEXT(text_id, description, category, rating) engine=TXN_BTREE PARTITION BY RANGE values(10) parameters(text_fields='{"description": {"tokenizer": {"type": "stem"}}, "category": {"tokenizer": {"type": "stem"}}, "rating": {"tokenizer": {"type": "i64"}}, "text_id": {"tokenizer": {"type": "i64"}}}'),        index diskann_index vector(diskann_id, feature) PARTITION BY RANGE values(2) parameters(type=diskann, metricType=L2, dimension=8, …
> [feat][index] Add DiskAnn vector type
