- CMakeLists.txt
- proto/common.proto
- proto/coordinator.proto
- proto/meta.proto
- proto/store.proto
- src/client/coordinator_client.cc
- src/coordinator/coordinator_service.cc
- src/coordinator/coordinator_service.h
- src/coordinator/main.cc
- src/store/main.cc
This PR add coordinator files and update CMakeLists.txt.
Now dingo-coordinator only support hello() request.
Also replace all copyright text with new version.
> [coordinator] Initial commit with only hello() support.

- .clang-format
- .clang-tidy
[dingo-poc] add .clang-format and .clang-tidy
> [dingo-poc] add .clang-format and .clang-tidy

- proto/common.proto
- proto/coordinator.proto
- proto/coordinator_internal.proto
- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/meta_client.cc
- src/client/store_client.cc
- src/common/context.h
- src/common/helper.cc
- src/common/helper.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/engine/engine.h
- src/engine/raft_kv_engine.cc
- src/engine/storage.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/raft/raft_node.cc
- src/raft/state_machine.cc
- src/server/coordinator_service.cc
- src/server/main.cc
- src/server/meta_service.cc
- src/server/meta_service.h
[proto][coordinator][common] Update meta/common/coordinator protos.
Fix some compile warnings.
Fix some clang-tidy warnings.
> Wip coordinator 20230301

- src/engine/engine.h
- src/engine/rocks_engine.cc
- src/engine/rocks_engine.h
[engine] add rocks engine KvPutIfAbsent and KvBatchPutIfAbsent interface implementation
> [engine] add rocks engine KvPutIfAbsent and KvBatchPutIfAbsent interface implementation

- .github/workflows/cmake.yml
- README.md
Add github action.
On push or pull request, github will trigger cmake action to compile the project.
> Wip GitHub action

- README.md
[doc] Fix github action badge url error.
> [doc] Fix github action badge url error.

- .gitmodules
- CMakeLists.txt
- cmake/lz4.cmake
- cmake/rocksdb.cmake
- cmake/yaml-cpp.cmake
- cmake/zstd.cmake
[cmake] Add lz4 & zstd for RocksDB.
> [cmake] Add lz4 & zstd for RocksDB.

- proto/coordinator_internal.proto
- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/meta_client.cc
- src/common/helper.cc
- src/common/helper.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/server/main.cc
- src/server/meta_service.cc
- src/server/meta_service.h
- src/server/server.cc
[server] Fix server start failed.
[meta] Fix CreateTable cannot store TableDefinition.
[meta] Add CreateTable & GetTable in meta_client.
CreateTable works now.
> All meta api work now

- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/engine/raft_kv_engine.cc
- src/engine/raft_kv_engine.h
- src/engine/storage.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/server/coordinator_service.cc
- src/server/main.cc
- src/server/server.cc
- src/server/server.h
- src/server/store_service.cc
- src/store/heartbeat.cc
- src/store/store_control.cc
[coordinator] Refactor region_map data structure.
[coordinator] Refactor storemap data structure.
[server] Fix Server::Recovery bug and Fix clang-tidy warnings.
> Wip coordinator 20230308

- conf/coordinator.yaml
- conf/store.yaml
- src/engine/rocks_engine.cc
- src/engine/rocks_engine.h
- test/test_rocks_engine.cc
[test, engine] Add rocksdb engine test case. fix  rocks engine bugs
> [test, engine] Add rocksdb engine test case. fix  rocks engine bugs

- CMakeLists.txt
[cmake] Make proto files build process able to incrementally build proto files.
> [cmake] Make proto files build process able to incrementally build proto

- src/coordinator/coordinator_control.cc
[meta] Fix GetTable voters information bug.
> [meta] Fix GetTable voters information bug.

- proto/common.proto
- proto/coordinator_internal.proto
- proto/node.proto
- src/client/coordinator_client.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/engine/write_data.h
- src/server/main.cc
- src/server/node_service.cc
- src/server/node_service.h
- src/server/server.cc
- src/server/server.h
[proto] Add NodeService, implement GetNodeInfo to get server & raft location in both server and raft port.
[proto,coordinator] Return the correct leader server_location for SDK if the server is not leader #68
> [proto,coordinator] Return the correct leader server_location for SDK if the server is not leader

- CMakeLists.txt
- src/coordinator/coordinator_control.cc
- src/meta/meta_writer.cc
- src/meta/meta_writer.h
- src/server/main.cc
[feat][coordinator] Use new KvBatchPutAndDelete interface to apply meta_increment.
> [feat][coordinator] Use new KvBatchPutAndDelete interface to apply meta_increment.

- conf/coordinator.template.yaml
- java/dingo-java-sdk-example/src/main/java/DingoJavaExampleUsingSDK.java
- java/pom.xml
- proto/push.proto
- proto/raft.proto
- scripts/stop.sh
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/crontab/crontab.cc
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/rocks_engine.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/server/coordinator_service.cc
- src/server/main.cc
- src/server/server.cc
- src/server/server.h
- src/store/heartbeat.cc
- src/store/heartbeat.h
[feat][common] Add push feature to dingo-store.
Now only create table will trigger coordinator to push storemap and
regionmap to affected stores, this will speed up out create table
process.
[fix][store] Fix raw_rocks_engine KvBatchPutAndDelete bug.
[fix][sdk] Fix sdk runtime error while building with maven.
[fix][sdk] Fix sdk example run failed first time on a dingo-store
> [feat][fix] New push feature and some severe bugfixes.

- scripts/clean_start_cluster.sh
- src/server/push_service.cc
- src/server/push_service.h
[fix][common] Add missing push_service source file.
[chore][deploy] Add a simple clean and build cluster script.
> [fix][common] Add missing push_service source file.

- CMakeLists.txt
[fix][common] Remove set CMAKE_BUILD_TYPE default to Debug.
> [fix][common] Remove set CMAKE_BUILD_TYPE default to Debug.

- CMakeLists.txt
- README.md
[fix][doc] Fix github action status badge in README.md.
[fix][common] Disable third party debug build type.
> [fix][common] Disable third party debug build type.

- proto/raft.proto
- proto/store.proto
[feat][proto] Add DeleteBatch feature.
> [feat][proto] Add DeleteBatch feature.

- proto/raft.proto
- proto/store.proto
[fix][proto]  Optimize DeleteBatch internal member function.
> [fix][proto]  Optimize DeleteBatch internal member function.

- src/engine/raw_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/write_data.h
- src/raft/store_state_machine.cc
- src/raft/store_state_machine.h
- src/server/store_service.cc
- src/server/store_service.h
- test/test_rocks_engine.cc
[feat][test,store]  Add DeleteBatch function. test DeleteBatch.
> [feat][test,store]  Add DeleteBatch function. test DeleteBatch.

- .clang-tidy
- proto/store.proto
- src/engine/raw_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/write_data.h
- src/raft/store_state_machine.cc
- src/server/store_service.cc
- src/server/store_service.h
- test/test_rocks_engine.cc
[feat][proto]  Add DeleteRange rpc .
[feat][test,store]  Add DeleteRange rpc implement .  test KvDeleteIfEqual .
[style][common] modify .clang-tidy
> [feat][test,proto,store]DeleteRange related

- proto/raft.proto
- proto/store.proto
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/write_data.h
- src/raft/store_state_machine.cc
- src/server/store_service.cc
- test/test_rocks_engine.cc
[fix][proto] refactoring  KvBatchPutIfAbsent function .
[refactor][store] refactoring KvBatchPutIfAbsent.
> [fix][proto] refactoring  KvBatchPutIfAbsent function .

- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- test/test_rocks_engine.cc
[style][store] Fix spelling mistakes in english words
> [style][store] Fix spelling mistakes in english words

- src/engine/engine.h
- src/engine/raw_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/rocks_engine.cc
- src/engine/rocks_engine.h
- test/test_rocks_engine.cc
[feat][store]  Multiple scans are supported under a single snapshot.
> [feat][store]  Multiple scans are supported under a single snapshot.

- proto/common.proto
- proto/store.proto
[feat][proto] Add scan rpc interface
> [feat][proto] Add scan rpc interface

- proto/store.proto
- src/engine/raw_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/handler/raft_handler.cc
- test/test_pb.cc
- test/test_rocks_engine.cc
[fix][proto] Fix KvPutIfAbsent and KvBatchPutIfAbsent rpc
[fix][store] Fix KvPutIfAbsent and KvBatchPutIfAbsent API
>  [fix][proto,store]  Fix KvPutIfAbsent and KvBatchPutIfAbsent

- .gitmodules
- CMakeLists.txt
- cmake/gperftools.cmake
- java/dingo-sdk/src/main/java/io/dingodb/client/RouteTable.java
- java/dingo-sdk/src/main/java/io/dingodb/client/ServiceOperation.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
- proto/coordinator.proto
- proto/coordinator_internal.proto
- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_meta.cc
- src/common/helper.cc
- src/common/meta_control.h
- src/coordinator/coordinator_closure.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/raft/meta_state_machine.cc
- src/raft/store_state_machine.cc
- src/server/coordinator_service.cc
- src/server/meta_service.cc
- src/server/meta_service.h
- src/server/node_service.cc
- src/server/push_service.cc
- src/store/heartbeat.cc
[fix][coordinator] Optimize coordinator on_apply and on_snapshot_load.
[fix][common] Replace MessageToJsonString to DebugString to reduce CPU usage and memory usage.
[feat][cmake] Add gperftools to cmake build.
> [feat] Optimze coordinator snapshot load and on_apply, add gperftools to dingo-store

- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_meta.cc
- src/common/safe_map.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_meta_storage.h
- src/server/coordinator_service.cc
- src/server/meta_service.cc
- src/server/meta_service.h
[feat][coordinator] Implement  GetSchemaByName and GetTableByName in coordinator.
[feat][common] Add Copy, Swap, Get, Count, Clear for SafeMap.
[fix][common] Fix return value of DingoSafeMap.
> [feat][coordinator] Implement  GetSchemaByName and GetTableByName

- proto/version.proto
- src/server/main.cc
- src/server/version_service.cc
- src/server/version_service.h
[feat][proto] Add version service provides listen for changes in vesion.
> [feat][proto] Add version service provides listen for changes in vesion.

- src/server/main.cc
- test/test_rocks_engine.cc
write_buffer_size: 4194304 will crash -> to  67108864
dbPath ->  ./rocks_example not root  permissions
> [fix][store] fix test_rocks_engine.cc crash .

- proto/meta.proto
[feat][proto] Add auto increment protocol in meta.proto
> [feat][proto] Add auto increment protocol in meta.proto

- src/coordinator/coordinator_closure.h
[fix][coordinator] Fix CoordinatorClosure memory leak.
> [fix][coordinator] Fix CoordinatorClosure memory leak.

- src/common/helper.cc
- src/common/helper.h
- src/engine/engine.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/meta_service.cc
- src/server/meta_service.h
- src/server/node_service.cc
- src/server/store_service.cc
Using type-alias for Errno for better code reading.
> [fix][server] Refactor type-aliasing Errno for better code reading

- proto/common.proto
- proto/coordinator.proto
- src/store/heartbeat.cc
- src/store/store_control.cc
[proto][common] Add StoreOperation protos.
> [proto][common] Add StoreOperation protos.

- proto/common.proto
- proto/coordinator.proto
- src/common/safe_map.h
[fix][proto] Add RegionDefinition in StoreHeartbeatRequest.
[refactor][common] Rename DingoSafeMap's Count() to Exists().
> [fix][proto] Add RegionDefinition in StoreHeartbeatRequest.

- proto/common.proto
- proto/coordinator.proto
- proto/coordinator_internal.proto
- src/common/safe_map.h
- src/coordinator/coordinator_closure.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_meta_storage.h
- src/server/server.cc
- src/store/heartbeat.cc
[feat][common] Add GetFlatMapCopy for DingoSafeMap.
[fix][proto] Update StoreMetrics and StoreOperation protos.
[feat][coordinator] Implement new heartbeat mechanism.
> [feat][coordinator] Implement new heartbeat mechanism.

- proto/coordinator.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/common/logging.h
- src/common/safe_map.h
- src/coordinator/coordinator_closure.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_meta_storage.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/node_service.cc
- src/store/heartbeat.cc
[fix][commom] Fix DingoSafeMap GetFlatMapCopy compile error.
[fix][common] Add ChangeLogLevel for dynamic change log level.
[fix][coordinator] Fix CreateTable generates StoreOperation.
[feat][common] Add GetAllKeyValues for DingoSafeMap.
[feat][coordinator] Add StoreOperation rpc client-side function implements.
[fix][coordinator] Fix a bunch of bugs of new heartbeat.
> [fix][coordinator] Fix a bunch of bugs of new heartbeat.

- CMakeLists.txt
- docker/conf/coordinator.template.yaml
- src/client/coordinator_client.cc
- src/client/store_client.cc
- src/common/version.cc
- src/common/version.h
- src/coordinator/coordinator_interaction.h
- src/server/main.cc
1、Version can be get from Client, such as `./bin/dingodb_client_store --show_version=true`
2、Version can be get from web of dingo-store
> Add version for dingo_server and clients

- proto/coordinator.proto
- proto/push.proto
- src/coordinator/coordinator_control_coor.cc
- src/server/push_service.cc
- src/server/push_service.h
- src/store/heartbeat.cc
- src/store/heartbeat.h
[feat][coordinator] Add new PushStoreOperation service in push_service.
> [feat][coordinator] Add new PushStoreOperation service in push_service.

- proto/common.proto
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/server/main.cc
- src/store/heartbeat.cc
- src/store/heartbeat.h
[fix][coordinator] Fix StoreOperation delete process with new mechanism.
[feat][coordinator] Implement StoreOperation delete process in new push service.
[fix][common] Add abort() and glog printf in signal handler.
[fix][coordinator] Upgrade Executor Hearbeat mechanism to new version.
> [feat] Update StoreOperation delete process to new version.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/store/StoreServiceClient.java
- proto/common.proto
- proto/raft.proto
- proto/store.proto
- src/common/helper.cc
- src/common/helper.h
- src/engine/engine.h
- src/engine/raft_kv_engine.cc
- src/engine/raft_kv_engine.h
- src/engine/raw_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/write_data.h
- src/handler/raft_handler.cc
- src/scan/scan.cc
- src/scan/scan.h
- src/server/store_service.cc
- test/test_rocks_engine.cc
- test/test_scan.cc
1. Add the number of returned deleted data.
2. Handle various range returns.
3. Process the last piece of data.
> [refactor][store] Refactor DeleteRange API.

- src/common/helper.cc
- src/common/helper.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- src/handler/raft_handler.cc
- src/server/store_service.cc
- test/test_rocks_engine.cc
[fix][store] Fix KvBatchPutIfAbsent API.
> [fix][store] Fix KvBatchPutIfAbsent API.

- proto/coordinator.proto
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/server/coordinator_service.cc
- src/store/heartbeat.cc
[feat][coordinator] Add split_from_region_id in CreateRegion region_cmd.
[fix][coordinator] Fix RpcSendPushStoreOperation location check.
> [feat][coordinator] Add split_from_region_id in CreateRegion region_cmd.

- java/dingo-mysql-init/pom.xml
- java/dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
- java/pom.xml
初始化表
mysql.user
mysql.db
mysql.tables_priv
information_schema.global_variables
> [feat][dingo-mysql-init] init mysql meta table

- proto/common.proto
- proto/coordinator.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_closure.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/engine/raft_meta_engine.cc
- src/engine/raft_meta_engine.h
- src/raft/raft_node.cc
- src/server/cluster_service.cc
- src/server/cluster_service.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/server.cc
- src/server/server.h
- src/store/heartbeat.cc
- src/store/heartbeat.h
[refactor][coordinator] Remove unused hearbeat mechanism.
[feat][coordinator] Implement new hearbeat's state update mechanism.
[feat][coordinator] Add GetOrphanRegion for coordinator service.
[fix][coordinator] Fix Region's replica_status and raft_status update in heartbeat.
> [refactor] Remove old heartbeat data structure.

- conf/store.template.yaml
- conf/store.yaml
- src/handler/raft_handler.cc
- src/scan/scan.cc
- src/scan/scan.h
- src/server/server.cc
- test/test_scan.cc
1. use the switch. enabled by default.
> [feat][store] Optimize scan performance. Increase asynchronous thread seek data.

- proto/coordinator_internal.proto
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/coordinator_service.cc
[fix][coordinator] Refresh TableRange after region split.
> [fix][coordinator] Refresh TableRange after region split.

- src/client/coordinator_client.cc
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control_coor.cc
[fix][coordinator] Fix ChangePeerRegion bug in coordinator.
> [fix][coordinator] Fix ChangePeerRegion bug in coordinator.

- proto/store.proto
- src/handler/raft_handler.cc
[refactor][store] Add BatchDelete every key state.
> [refactor][store] Add BatchDelete every key state.

- java/dingo-mysql-init/pom.xml
- java/dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
- java/dingo-mysql-init/src/main/resources/table-information-global_variables.json
- java/dingo-mysql-init/src/main/resources/table-mysql-db.json
- java/dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json
- java/dingo-mysql-init/src/main/resources/table-mysql-user.json
1. init mysql meta table using storeServiceClient
2. read table definition from json config
> [feat][dingo-mysql-init] Init mysql meta table from config

- proto/coordinator.proto
- src/coordinator/coordinator_control_coor.cc
- src/store/heartbeat.cc
[feat][coordinator] Add PurgeRequest in RegionCmd to purge region meta after delete region.
> [feat][coordinator] Add PurgeRequest in RegionCmd to purge region meta

- proto/coordinator.proto
- proto/coordinator_internal.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/server.cc
- src/store/heartbeat.cc
- src/store/heartbeat.h
[feat][coordinator] Implement a TaskList mechanism to do region split in one step.
[feat][coordinator] Use TaskList to do SplitRegion.
> [feat][coordinator] Use TaskList to do SplitRegion.

- proto/coordinator_internal.proto
- src/client/coordinator_client_function_auto_increment.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] Fix table_name wrongly conflict across schemas.
> [fix][coordinator] Fix table_name wrongly conflict across schemas.

- proto/coordinator_internal.proto
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
[refactor][coordinator] Remove used schema_id in MetaIncrement protobuf message.
> [refactor][coordinator] Remove used schema_id in MetaIncrement protobuf

- src/handler/raft_handler.cc
[fix][store] Fix DeleteRegion  return delete count wrong  bug.
> [fix][store] Fix DeleteRegion  return delete count wrong  bug.

- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/event/store_state_machine_event.cc
- src/store/heartbeat.cc
[fix][store] Update Region Definition Peer info after change peer.
[fix][coordinator] Stop resend store operation when store response with EREGION_CMD_ONGOING_CONFLICT.
> [fix] Fix GetTableRange after shrink region.

- proto/coordinator.proto
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/server/coordinator_service.cc
- src/store/region_controller.cc
[feat][coordinator] Add automatic region purge after shrink region.
[fix][store] Fix region purge bug.
> [feat][coordinator] Add automatic region purge after shrink region.

- src/coordinator/coordinator_control_coor.cc
- src/store/heartbeat.cc
[fix][coordinator] Fix unable to delete table after drop table.
> [fix][coordinator] Fix unable to delete table after drop table.

- scripts/deploy_server.sh
- scripts/start_server.sh
- scripts/stop.sh
- src/coordinator/coordinator_interaction.cc
- src/coordinator/coordinator_interaction.h
- src/server/main.cc
- src/server/server.cc
- src/server/server.h
[feat][common] Refactor CoordinatorInteraction to support name services.
> [feat][common] Refactor CoordinatorInteraction to support name services.

- src/coordinator/coordinator_interaction.h
[fix][common] Setup leader after using name service channel call method success, this will reduce count of reconnect to coordinators.
> [fix][common] Setup leader after using name service channel call method

- java/dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
> [fix][dingo-mysql-init] Fix bug: add init exit code

- src/coordinator/auto_increment_control.cc
- src/coordinator/coordinator_control.cc
[fix][coordinator] Init leader_term in meta_control constructor function.
> [fix][coordinator] Init leader_term in meta_control constructor

- proto/coordinator.proto
- scripts/deploy_server.sh
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/store/heartbeat.cc
[feat][coordinator] Add store,region,table bvars memory info in Hello rpc call.
[feat][coordinator] Add store, region, table bvars for coordinator.
[fix][deploy] Fix deploy.sh faild in multi-user environment.
> [feat][coordinator] Add store, region, table bvars for coordinator.

- src/common/meta_control.h
- src/coordinator/auto_increment_control.cc
- src/coordinator/auto_increment_control.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_fsm.cc
- src/raft/meta_state_machine.cc
[feat][coordinator] Add new is_leader bvar for coordinator.
> [feat][coordinator] Add new is_leader bvar for coordinator.

- src/client/coordinator_client.cc
- src/client/coordinator_client_function_meta.cc
- src/coordinator/auto_increment_control.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_interaction.h
[fix][coordinator] Fix CreateTable failed if retry create auto increment.
[feat][coordinator] Add replica parameter for coordinator_client.
> [fix][coordinator] Fix CreateTable failed if retry create auto increment.

- .gitmodules
- CMakeLists.txt
- cmake/fmt.cmake
- proto/node.proto
- src/common/safe_map.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/metrics/coordinator_bvar_metrics.h
- src/metrics/dingo_bvar.h
- src/server/node_service.cc
- src/server/node_service.h
- src/server/server.cc
- src/store/heartbeat.cc
[feat] Add Multi Dimension bvar for cooordinator.
[feat] Update brpc, rocksdb etc. version.
[feat] Add fmt lib for faster string format.
[fix] Fix drop table cause coordinator core dump.
[fix] Temporarily add a new rpc call to support Prometheus metrics.
Now we can temporarily use http://host:port/NodeService/DingoMetrics to get Prometheus metrics.
> [fix] Fix drop table cause coordinator core dump

- proto/coordinator.proto
- proto/error.proto
- scripts/deploy_func.sh
- scripts/docker-dingo-store.sh
- scripts/mysql_init.sh
- scripts/stop.sh
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/metrics/coordinator_bvar_metrics.h
- src/metrics/dingo_bvar.h
- src/raft/raft_node.cc
- src/raft/raft_node.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
[feat] Add TransferLeaderRegion in coordinator
> [feat] Add TransferLeaderRegion in coordinator

- scripts/docker-dingo-store.sh
- scripts/stop.sh
[fix][deploy] Fix stop failed.
> [fix][deploy] Fix stop failed.

- proto/coordinator.proto
- src/common/helper.h
- src/coordinator/coordinator_control_coor.cc
- src/server/coordinator_service.cc
- src/server/main.cc
[fix][coordinator] Use Peer in TransferLeaderRequest for store.
> [fix][coordinator] Use Peer in TransferLeaderRequest for store.

- src/metrics/coordinator_bvar_metrics.h
[feat][coordinator] Add Store used space percent metrics for Prometheus.
> [feat][coordinator] Add Store used space percent metrics for Prometheus.

- .gitmodules
- CMakeLists.txt
- cmake/libbacktrace.cmake
- src/metrics/coordinator_bvar_metrics.h
- src/server/main.cc
[feat][common] Print source code file and line number when printing stack trace info.
> [feat][common] Print source code file and line number when printing

- java/dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
expanding variables:
auto_increment_offset
protocol_version
port
store_engine
have_ssl
have_statement_timeout
connect_timeout
max_execution_time
> [feat][dingo-mysql-init] Expanding global variables

- conf/coordinator.template.yaml
- proto/coordinator.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/common/helper.cc
- src/common/helper.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/main.cc
- src/store/heartbeat.cc
[feat][coordinator] Implement a simple region distribute algorithm.
[feat][coordinator] Add UpdateStore rpc call to update store state of IN/OUT.
[fix][store] Fix delete store bug in heartbeat.
> [feat][coordinator] Implement a simple region distribute algorithm.

- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/store/heartbeat.cc
[refactor][coordinator] Refactor TaskList generating code.
[refactor][coordinator] Refactor StoreOperation send mechanism.
> [refactor][coordinator] Refactor TaskList generating code.

- java/dingo-sdk/pom.xml
- java/dingo-sdk/src/main/java/io/dingodb/client/OperationService.java
- java/dingo-sdk/src/main/java/io/dingodb/client/operation/ScanOperation.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/RecordEncoder.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/Parameters.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/AutoIncrementServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/ChannelManager.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/CoordinatorServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/MetaServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/ServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/StoreServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/store/StoreServiceClient.java
- java/pom.xml
[fix][sdk] Fix unlimited refreshing of route table
> [fix][sdk] Fix unlimited refreshing of route table

- src/common/safe_map.h
- src/coordinator/coordinator_control_coor.cc
- src/serial/buf.cc
- src/serial/buf.h
- src/serial/keyvalue.cc
- src/serial/keyvalue.h
- src/serial/keyvalue_codec.cc
- src/serial/keyvalue_codec.h
- src/serial/record_decoder.cc
- src/serial/record_decoder.h
- src/serial/record_encoder.cc
- src/serial/record_encoder.h
- src/serial/schema/boolean_schema.cc
- src/serial/schema/boolean_schema.h
- src/serial/schema/double_schema.cc
- src/serial/schema/integer_schema.cc
- src/serial/schema/long_schema.cc
- src/serial/schema/string_schema.cc
- src/serial/schema/string_schema.h
- src/serial/utils.cc
- src/serial/utils.h
- test/test_safe_map.cc
- test/test_serial.cc
[refactor][common] Refactor serial code for computation push-down.
[fix][common] Add unit test for DingoSafeMap.
> [refactor][common] Refactor serial code for computation push-down.

- proto/store.proto
- src/serial/keyvalue_codec.cc
- src/serial/keyvalue_codec.h
- src/serial/record_decoder.cc
- src/serial/record_decoder.h
- src/serial/record_encoder.cc
- src/serial/record_encoder.h
- test/test_serial.cc
[feat][proto] Add coprocessor proto
[fix][serial] Fix serial bug and tidy code.
> [feat,fix][proto,serial] Add coprocessor proto. Fix serial bug and tidy code.

- src/serial/keyvalue.cc
- src/serial/keyvalue.h
- src/serial/keyvalue_codec.cc
- src/serial/keyvalue_codec.h
- src/serial/record_decoder.cc
- src/serial/record_decoder.h
- src/serial/record_encoder.cc
- src/serial/record_encoder.h
- src/serial/utils.cc
- src/serial/utils.h
- test/test_serial.cc
[refactor][common] Refactor serial code, use shared_ptr.
[refactor][common] Refactor KeyValue and KeyValueCodec.
> [refactor][common] Refactor serial code, use shared_ptr.

- src/serial/utils.cc
- src/serial/utils.h
[fix][common] Remove usused serial functions.
> [fix][common] Remove usused serial functions.

- src/server/service_helper.cc
- src/server/store_service.cc
[fix][store] Fix scan param check. if range invalid return no error.
> [fix][store] Fix scan param check. if range invalid return no error.

- test/test_service_helper.cc
[test][store] Add ServiceHelper ValidateRangeWithOptions test.
> [test][store] Add ServiceHelper ValidateRangeWithOptions test.

- conf/coordinator.template.yaml
- proto/coordinator.proto
- proto/meta.proto
- scripts/stop.sh
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/coordinator_client_function_meta.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_interaction.h
- src/metrics/dingo_bvar.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/meta_service.cc
- src/server/meta_service.h
- src/store/heartbeat.cc
- src/store/heartbeat.h
[fix][coordinator] Fix GetSchemaByName cannot return root schema bug.
[fix][coordinator] Fix heartbeat timeout and improve coordinator performance.
> [fix][coordinator] Fix bugs & impove coordinator performance

- CMakeLists.txt
- proto/store.proto
- src/coprocessor/aggregation.cc
- src/coprocessor/aggregation.h
- src/coprocessor/aggregation_manager.cc
- src/coprocessor/aggregation_manager.h
- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor.h
- src/coprocessor/utils.cc
- src/coprocessor/utils.h
- src/engine/storage.cc
- src/engine/storage.h
- src/scan/scan.cc
- src/scan/scan.h
- src/scan/scan_filter.cc
- src/scan/scan_filter.h
- src/serial/record_decoder.cc
- src/serial/record_decoder.h
- src/server/store_service.cc
- test/test_coprocessor.cc
- test/test_coprocessor_aggregation_manager.cc
- test/test_coprocessor_utils.cc
- test/test_scan.cc
- test/test_scan_with_coprocessor.cc
1. Support selection.
2. Support expression filtering.
3. Support simple aggregation Each aggregation operator is for a certain column.
> [feat][store] Add coprocessor.

- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/server/cluster_service.cc
[fix][coordinator] Fix Cluster Info missed leader and follower info in web console.
> [fix][coordinator] Fix Cluster Info missed leader and follower info

- src/client/coordinator_client.cc
- src/client/coordinator_client_function_coor.cc
- src/common/helper.cc
- src/common/helper.h
[fix][coordinator] Fix split watershed key calculation.
> [fix][coordinator] Fix split watershed key calculation.

- java/dingo-mysql-init/src/main/java/io/dingodb/mysql/MysqlInit.java
- java/dingo-mysql-init/src/main/resources/table-mysql-db.json
- java/dingo-mysql-init/src/main/resources/table-mysql-tables_priv.json
- java/dingo-mysql-init/src/main/resources/table-mysql-user.json
1.  table user field name user -> name
> [fix][dingo-mysql-init] Fix bug: table user field name user -> name

- README.md
- scripts/deploy_func.sh
[fix][deploy] Fix missed unlink when deploy_funcs.
> [fix][deploy] Fix missed unlink when deploy_funcs.

- proto/store.proto
> [feat][proto] Add Sum0.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/DingoClientException.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/partition/PartitionRule.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/schema/BooleanSchema.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/AutoIncrementServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/CoordinatorServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/MetaServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/ServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/StoreServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/store/AggregationOperator.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/store/StoreServiceClient.java
[feat][sdk] Add split region for meta service client
> [feat][sdk] Add split region for meta service client

- proto/common.proto
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/store/heartbeat.cc
[fix][coordinator] Fix DropRegion cause residue region info in RegionMap in some corner cases.
> [fix][coordinator] Fix DropRegion cause residue region info in RegionMap

- proto/store.proto
- src/coprocessor/aggregation.cc
- src/coprocessor/aggregation.h
- src/coprocessor/aggregation_manager.cc
- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor.h
- src/coprocessor/utils.cc
- src/coprocessor/utils.h
- src/serial/record_decoder.cc
- test/test_coprocessor.cc
- test/test_coprocessor_utils.cc
[fix][store] Fix coprocessor bugs.
> [fix][store] Fix coprocessor bugs.

- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
[fix][coordinator] Fix region update when heartbeat arrived after DropRegion.
> [fix][coordinator] Fix region update when heartbeat arrived after

- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] Fix TableMetics update in background.
> [fix][coordinator] Fix TableMetics update in background.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/codec/CodecUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/codec/DingoKeyValueCodec.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/ColumnDefinition.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/ErrorCodeUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/ServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/store/AggregationOperator.java
[fix][sdk] Fix codec schema order
> [fix][sdk] Fix codec schema order

- src/coprocessor/utils.cc
- test/test_coprocessor.cc
- test/test_scan_with_coprocessor.cc
[test][store] Perfect coprocessor  test case
> [test][store] Perfect coprocessor  test case

- src/coprocessor/aggregation_manager.cc
- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor.h
- src/coprocessor/utils.cc
- src/coprocessor/utils.h
- src/scan/scan.cc
- src/scan/scan.h
- src/serial/schema/base_schema.h
- test/test_coprocessor_aggregation_manager.cc
1. sum<string, string> return exception.
2. solve the problem of schema disorder
> [fix][store] Fix coordinator bugs.

- .clang-tidy
- proto/common.proto
- proto/coordinator.proto
- proto/coordinator_internal.proto
- scripts/deploy_func.sh
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/coordinator_client_function_incr.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/metrics/store_metrics_manager.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/store/heartbeat.cc
- src/store/region_controller.cc
- src/store/region_controller.h
[feat][coordinator] Add DeleteRegionMap for coordinator.
> [feat][coordinator] Add DeleteRegionMap for coordinator.

- proto/coordinator.proto
- src/coordinator/coordinator_control_coor.cc
[feat][coordinator] Add DeletedRegionMap to MemoryInfo.
> [feat][coordinator] Add DeletedRegionMap to MemoryInfo.

- src/client/coordinator_client_function_coor.cc
- src/client/coordinator_client_function_meta.cc
- src/common/helper.cc
- src/common/helper.h
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_meta_storage.h
- src/coprocessor/coprocessor.cc
[fix][coordinator] Fix load raft snapshot for DeletedRegion.
> [fix][coordinator] Fix load raft snapshot for DeletedRegion.

- CMakeLists.txt
- src/client/coordinator_client.cc
- src/common/version.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/main.cc
[fix][coordinator] Fix GetCoordinatorMap when not leader is found. Fix GetTableByName error log print.
[feat][common] Add CMAKE_BUILD_TYPE print in show_version.
> [fix][coordinator] Fix GetCoordinatorMap when not leader is found.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/AutoIncrement.java
- java/dingo-sdk/src/test/java/sdk/common/AutoIncrementTest.java
[fix][sdk] Fix increment calc inc
> [fix][sdk] Fix increment calc inc

- src/client/coordinator_client.cc
- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control_coor.cc
- src/engine/raft_kv_engine.cc
- src/handler/raft_snapshot_handler.cc
- src/server/main.cc
- src/server/server.cc
[fix][coordinator] Fix incorrect calling LoadIndex for non-index region's Add Node.
> [fix][coordinator] Fix incorrect calling LoadIndex for non-index

- src/server/main.cc
- src/server/server.cc
[fix][common] Fix unit test compiling.
> [fix][common] Fix unit test compiling.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- proto/common.proto
[fix][index] Fix ScalarIndex type name.
> [fix][index] Fix ScalarIndex type name.

- proto/coordinator_internal.proto
- proto/meta.proto
- scripts/clean_start_cluster.sh
- scripts/deploy_func.sh
- scripts/deploy_server.sh
- src/client/coordinator_client.cc
- src/client/coordinator_client_function_meta.cc
- src/common/constant.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control_meta.cc
- src/handler/raft_handler.cc
- src/handler/raft_snapshot_handler.cc
- src/vector/codec.cc
- src/vector/codec.h
- src/vector/vector_index.h
- src/vector/vector_index_manager.cc
- src/vector/vector_index_manager.h
[feat][coordinator] Add auto increment creating for CreateIndex.
[feat][index] Implement VectorIndex Rebuild mechanism.
> [feat][coordinator] Add auto increment creating for CreateIndex.

- proto/common.proto
[feat][proto] Support scalar index.
> [feat][proto] Support scalar index.

- proto/common.proto
- src/client/store_client_function.cc
- src/common/constant.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_meta.cc
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/handler/raft_handler.cc
- src/vector/codec.cc
- src/vector/codec.h
- src/vector/vector_index_manager.h
[fix][coordinator] Add ValidateIndexDefinition to check create index parameter.
> [fix][coordinator] Add ValidateIndexDefinition to check create index

- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- test/test_vector_index_flat.cc
[fix][test] Add Vector flat test and fix bugs.
> [fix][test] Add Vector flat test and fix bugs.

- CMakeLists.txt
- proto/common.proto
- src/common/helper.cc
- src/common/helper.h
- src/coordinator/coordinator_control_coor.cc
- src/handler/raft_handler.cc
- src/handler/raft_snapshot_handler.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/metrics/store_metrics_manager.cc
- src/server/service_helper.cc
- src/store/region_controller.cc
Index region need raw range to make vector data share one RocksDB.
> [feat][common] Add raw_range in RegionDefinition.

- proto/coordinator.proto
- proto/meta.proto
- src/client/coordinator_client.cc
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_meta.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_meta.cc
- src/crontab/crontab.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/server/cluster_service.cc
- src/server/cluster_service.h
- src/server/meta_service.cc
- src/server/meta_service.h
- src/store/region_controller.cc
- src/store/region_controller.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
[feat][coordinator] Add UpdateIndex for coordinator.
[feat][index] Implement UpdateDefinition for index.
[feat][coordinator] Add Index information in brpc web.
[fix][index] Update RegionDefinition in StoreMeta when updating IndexParameter.
> [feat][index] Implement UpdateDefinition for index.

- src/client/coordinator_client.cc
- src/client/store_client.cc
- src/common/version.cc
- src/common/version.h
- src/server/main.cc
- src/server/server.cc
[feat][common] Add major and minor version.
> [feat][common] Add major and minor version.

- src/handler/raft_handler.cc
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_manager.cc
- src/vector/vector_index_snapshot.cc
[fix][index] Fix RebuildVectorIndex hang vector index update.
> [fix][index] Fix RebuildVectorIndex hang vector index update.

- src/client/store_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- test/test_vector_index_flat.cc
- test/test_vector_index_memory.cc
- test/test_vector_index_memory_flat.cc
- test/test_vector_index_memory_hnsw.cc
[test][store] Test hnsw and flat add performance comparison.
> [test][store] Test hnsw and flat add performance comparison.

- src/common/helper.cc
- src/common/helper.h
- src/engine/raft_store_engine.cc
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_manager.cc
- src/vector/vector_index_manager.h
- src/vector/vector_index_snapshot.cc
- test/test_helper.cc
[fix][index] Fix FlatIndex's search without-vector parameter not work.
[fix][index] Fix bugs of VectorIndex snapshot save/load.
> [fix] VectorIndex Snap bugs & FlatIndex bugs.

- proto/common.proto
- proto/index.proto
- src/client/store_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/engine/engine.h
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/handler/raft_handler.cc
- src/server/index_service.cc
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
[refactor][index] Use parallel add and del to accelerate VectorAdd and VectorDelete.
> [refactor][index] Use parallel add and del to accelerate VectorAdd

- conf/index.template.yaml
- src/handler/raft_snapshot_handler.cc
- src/log/segment_log_storage.h
- src/server/server.cc
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- src/vector/vector_index_manager.cc
- src/vector/vector_index_manager.h
- src/vector/vector_index_snapshot.cc
- src/vector/vector_index_snapshot.h
[feat][index] Implement SaveVectorIndexSnapshot with fork().
[fix][index] Fix ScrubVectorIndex status check bug.
> [feat][index] Implement SaveVectorIndexSnapshot with fork().

- proto/common.proto
- proto/index.proto
- src/client/store_client.cc
- src/client/store_client_function.cc
- src/common/constant.h
- src/common/helper.cc
- src/common/helper.h
- src/engine/engine.h
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/handler/raft_handler.cc
- src/server/index_service.cc
- src/vector/codec.cc
- src/vector/codec.h
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- src/vector/vector_index_manager.cc
- test/test_vector_index_flat.cc
- test/test_vector_index_memory_flat.cc
- test/test_vector_index_memory_hnsw.cc
[fix][index] Re-org VectorIndex's interface, optimize dingodb_clent_store's speed test mechinism.
[feat][index] Add TableData for VectorWithId.
> [feat][index] Add TableData for VectorWithId

- proto/common.proto
[feat][proto] Add vetor index metrics proto.
> [feat][proto] Add vetor index metrics proto.

- proto/common.proto
- proto/index.proto
- src/client/store_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/engine/engine.h
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/server/index_service.cc
- src/server/index_service.h
- src/vector/codec.cc
- src/vector/codec.h
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- src/vector/vector_index_manager.cc
- src/vector/vector_index_manager.h
[feat][index] Add VectorScanQuery and VectorGetRegionMetrics.
> [feat][index] Add VectorScanQuery and VectorGetRegionMetrics.

- src/client/client_interation.h
- src/engine/raft_store_engine.cc
- src/engine/storage.h
- src/server/index_service.cc
- src/server/index_service.h
[fix][index] Fix ScanQuery border check.
[fix][index] Check is_leader before check vector_index in vector apis.
> [fix][index] Fix ScanQuery border check.

- proto/common.proto
- src/client/coordinator_client_function_meta.cc
- src/vector/vector_index.cc
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- test/test_vector_index_flat.cc
- test/test_vector_index_hnsw.cc
[feat][index] Implement cosine metric type for vector index.
> [feat][index] Implement cosine metric type for vector index.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
- proto/common.proto
- proto/meta.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_meta.cc
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/server/meta_service.cc
- src/server/meta_service.h
[feat][proto] Refactor table operations for adding scalar index.
> [feat][proto] Refactor table operations for adding scalar index.

- src/vector/vector_index_flat.cc
- test/test_vector_index_hnsw.cc
[fix][index] Fix inner product, cosine distance and similariy relativity order.
> [fix][index] Fix inner product, cosine distance and similariy relativity

- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor.h
- src/coprocessor/utils.cc
- src/serial/counter.h
- src/serial/record_decoder.cc
- src/serial/utils.cc
- src/serial/utils.h
- test/test_serial_selection.cc
[fix][store] Fix coprocessor selection function
> [fix][store] Fix coprocessor selection function

- proto/index.proto
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/engine/storage.cc
- src/engine/storage.h
- src/server/index_service.cc
- src/server/index_service.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- src/vector/vector_index_utils.cc
- src/vector/vector_index_utils.h
- test/test_vector_index_hnsw.cc
- test/test_vector_index_utils.cc
[feat][index] Add calculate distance api.
>  [feat][index] Add calculate distance api.

- proto/coordinator_internal.proto
- proto/version.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_kv.cc
- src/client/dingodb_client.cc
- src/common/safe_map.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_kv.cc
- src/coordinator/coordinator_control_lease.cc
- src/coordinator/coordinator_meta_storage.h
- src/server/version_service.cc
- src/server/version_service.h
[feat] Imlement MVCC key value storage in coordinator.
> [feat] Imlement MVCC key value storage in coordinator.

- proto/common.proto
[feat][index] Refactor vector search filter.
> [feat][index] Refactor vector search filter.

- src/client/coordinator_client_function_lease.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_kv.cc
- src/coordinator/coordinator_control_lease.cc
- src/server/version_service.cc
[feat][coordinator] Implement Lease mechanism.
[feat][common] Bump up brpc version to 1.6.0.
> [feat][coordinator] Implement Lease mechanism.

- proto/meta.proto
- src/coordinator/coordinator_control_meta.cc
- src/server/meta_service.cc
[refactor][proto] update proto file about index after adding part_id.
> [refactor][proto] update proto file about index after adding part_id.

- proto/meta.proto
- src/client/coordinator_client_function_meta.cc
- src/common/helper.cc
- src/coordinator/coordinator_control_meta.cc
[feat][coordinator] Add new Partition definition for PartitionRule.
Fix VectorIndex's Range.
> [feat][coordinator] Add new Partition definition for PartitionRule.

- proto/version.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_watch.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_kv.cc
- src/coordinator/coordinator_control_watch.cc
- src/coordinator/coordinator_interaction.h
- src/server/version_service.cc
- src/server/version_service.h
- src/store/heartbeat.cc
[feat] Implement Watch mechanism.
> [feat] Implement Watch mechanism.

- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_watch.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_kv.cc
- src/coordinator/coordinator_control_lease.cc
- src/server/version_service.cc
[feat][coordinator] Implement Lock in dingodb_client.
[feat][coordinator] Implement deleted_count in KvDeleteRange.
[fix][coordinator] Fix dead lock in LeaseRevoke.
> [feat][coordinator] Implement Lock in dingodb_client

- src/coordinator/coordinator_control_meta.cc
- src/server/meta_service.cc
[fix][coordinator] Fix scalar index interface while debugging.
> [fix][coordinator] Fix scalar index interface while debugging.

- src/client/coordinator_client_function_coor.cc
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/server/coordinator_service.cc
[fix][coordinator] Fix SplitRegion update table/index partitions lost in parallel processing.
> [fix][coordinator] Fix SplitRegion update table/index partitions lost in

- conf/coordinator.template.yaml
- conf/coordinator.yaml
- proto/coordinator_internal.proto
- proto/version.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_kv.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_kv.cc
- src/coordinator/coordinator_control_lease.cc
- src/coordinator/coordinator_control_watch.cc
- src/server/server.cc
- src/server/version_service.cc
- src/server/version_service.h
[feat][coordinator] Implement KvCompaction mechanism in coordinator.
> [feat][coordinator] Implement KvCompaction mechanism in coordinator.

- conf/index.yaml
- proto/common.proto
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/vector/vector_index.h
- src/vector/vector_index_filter.cc
- src/vector/vector_index_filter.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- test/test_vector_index_flat_search_param.cc
- test/test_vector_index_hnsw_search_param.cc
[feat][index] Add vector index scalar pre-filter.
[feat][index] Add vector index id array search.
[feat][index] Add vector index search original interface support pre-filter
>  [feat][index] Add vector index pre-filter.

- proto/common.proto
- src/common/helper.cc
- src/common/helper.h
- src/common/safe_map.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_kv.cc
- src/metrics/store_metrics_manager.cc
- src/store/store_controller.h
- test/test_helper.cc
- test/test_safe_map.cc
[feat][coordinator] Optimize KvRange from table full scan to table range scan.
[feat][coordinator] Add store weight calculation algorithm for create vector index region.
> [feat][coordinator] Optimize KvRange from table full scan to table range scan.

- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
[fix][index] Optimize FlatRangeFilter to reduce memory copy during vector search.
> [fix][index] Optimize FlatRangeFilter to reduce memory copy during

- src/vector/vector_index_hnsw.cc
[fix][index] Fix hnsw current_count and deleted_count metrics.
> [fix][index] Fix hnsw current_count and deleted_count metrics.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/index/IndexServiceClient.java
- proto/common.proto
- src/vector/vector_reader.cc
[refactor][index] Remove VectorSearch proto use_scalar_filter field.
> [refactor][index] Remove VectorSearch proto use_scalar_filter field.

- src/vector/vector_reader.cc
[fix][index] Fix vector index pre-filter bug.
> [fix][index] Fix vector index pre-filter bug.

- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/coordinator/coordinator_control_meta.cc
- src/vector/vector_reader.cc
[fix][index] Fix ScalarFilter bug when the filter key is not exists.
[fix][coordinator] Fix GetIndexRange return part_id.
> [fix][index] Fix ScalarFilter bug when the filter key is not exists.

- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] fix DropTables when no index found in table.
> [fix][coordinator] fix DropTables when no index found in table.

- src/vector/vector_index_hnsw.cc
- test/test_vector_index_flat_search_param.cc
- test/test_vector_index_hnsw_search_param.cc
[feat][index] Add the order of hnsw search results. from small to large.
> [feat][index] Add the order of hnsw search results. from small to large.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- proto/common.proto
- proto/store.proto
- src/coprocessor/utils.cc
[fix][store] Fix queries containing array types
> [fix][store] Fix queries containing array types

- src/vector/vector_index_hnsw.cc
- src/vector/vector_reader.cc
- test/test_vector_index_hnsw_search_param.cc
[feat][index] Hnsw search results insufficient topk will not report an error. output result.
[test][index] Add post scalar filter rocksdb kv get time statistics and support SQL optimization.
> [feat][index] Hnsw search results insufficient topk will not report an error. output result.

- CMakeLists.txt
- test/test_google_sanitize.cc
[feat][cmake] Add google sanitize. default disable.use -DBUILD_GOOGLE_SANITIZE=ON enable.
> [feat][cmake] Add google sanitize. default disable.use -DBUILD_GOOGLE_SANITIZE=ON enable.

- test/test_vector_index_flat.cc
- test/test_vector_index_flat_search_param.cc
- test/test_vector_index_hnsw.cc
- test/test_vector_index_hnsw_search_param.cc
- test/test_vector_index_memory.cc
- test/test_vector_index_memory_flat.cc
- test/test_vector_index_memory_hnsw.cc
[test][index] Fix vetor index test compile error.
> [test][index] Fix vetor index test compile error.

- test/test_google_sanitize.cc
[test][common] Enrich google sanitize test .
> [test][common] Enrich google sanitize test .

- proto/coordinator.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
[feat][coordinator] Add disk capacity and memory check for CreateRegion.
[feat][coordinator] Add CreateRegionId rpc call.
[fix][coordinator] Fix CreateIndex partial fail while CreateRegion failed.
> [feat][coordinator] Add disk capacity and memory check for CreateRegion.

- proto/coordinator.proto
- src/client/coordinator_client_function_coor.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/server/coordinator_service.cc
[feat][coordinator] Add CreateShadowRegion for post-create-region split.
> [feat][coordinator] Add CreateShadowRegion for post-create-region split.

- conf/coordinator-gflags.conf
- conf/index-gflags.conf
- conf/store-gflags.conf
- scripts/deploy_func.sh
- src/client/dingodb_client.cc
- src/common/helper.cc
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/tso_control.cc
- src/server/main.cc
- src/server/meta_service.cc
Now we can run dingodb_server in dist/{role} directory with no command line parameters.  All gflags parameters can be changed its default value in conf/gflags.conf file.
Also we can run dingodb_client with many gflags file for testing during develop period.
> [fix][coordinator] Fit max hnsw elements parameter into 4GB of region.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/vector/VectorScanQuery.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/vector/VectorSearchParameter.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/index/IndexServiceClient.java
- proto/common.proto
- proto/index.proto
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/engine/storage.cc
- src/engine/storage.h
- src/server/index_service.cc
- src/vector/vector_reader.cc
Change with_table_data/scalar_data to without.
> [fix][index] Refactor Vector parameters.

- proto/meta.proto
- src/client/client_helper.h
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/coordinator_client_function_meta.cc
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] Remove unused range_partition and hash_partition in proto.
> [fix][coordinator] Remove unused range_partition and hash_partition in proto.

- proto/meta.proto
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] Fix SelectStore memory calculation using available_memory to replace free_memory.
> [fix][coordinator] Fix SelectStore memory calculation using

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
[fix][sdk] Fix hash partition strategy problem
> [fix][sdk] Fix hash partition strategy problem

- src/client/coordinator_client_function_incr.cc
- src/coordinator/auto_increment_control.cc
[fix][coordinator] Fix auto increment when loading snapshot.
> [fix][coordinator] Fix auto increment when loading snapshot.

- src/common/helper.cc
- src/common/helper.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_interaction.h
- src/server/meta_service.cc
- src/store/heartbeat.cc
Limit default max partition count of table/index to 1024.
> [fix][coordinator] Enlarge coordinator interaction default.

- conf/coordinator-gflags.conf
- conf/index-gflags.conf
- conf/store-gflags.conf
- src/coordinator/tso_control.cc
- src/server/index_service.cc
- src/server/main.cc
- src/vector/vector_index_snapshot.cc
[fix][index] Fix vector index IsBuildError() check bug.
[feat][common] Add h2 options gflags to increase stream_window_size and connection_window_size to 1GB.
[fix][coordinator] Fix possible tso fallback.
> [fix] Fix tso & IsBuildError check

- conf/coordinator-gflags.conf
- conf/index-gflags.conf
- conf/store-gflags.conf
- proto/common.proto
- proto/coordinator.proto
- proto/coordinator_internal.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/dingodb_client.cc
- src/common/safe_map.h
- src/common/syscheck.cc
- src/common/syscheck.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_kv.cc
- src/coordinator/coordinator_control_lease.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/index_service.cc
- src/server/main.cc
- src/server/meta_service.cc
- src/server/util_service.cc
- src/store/heartbeat.cc
- src/vector/vector_index_hnsw.cc
- test/test_safe_map.cc
1. Improve coordinator heartbeat performance.
2. Support fast follower update region definition.
3. Region status now store as cache, do not apply to raft.
> [refactor][coordinator] Refactor coordinator's hearbeat.

- src/common/safe_map.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/cluster_service.cc
- src/store/heartbeat.cc
[fix][coordinator] Fix DropTable's drop region competing with auto split.
> [fix][coordinator] Fix DropTable's drop region competing with auto

- src/server/push_service.cc
- src/store/heartbeat.cc
[fix][coordinator] Fix split region_cmd's re-routing when ERAFT_NOTLEADER.
> [fix][coordinator] Fix split region_cmd's re-routing when

- proto/coordinator_internal.proto
- proto/meta.proto
- src/client/client_interation.h
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_meta.cc
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/coordinator/coordinator_control.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/index_service.cc
- src/server/index_service.h
- src/server/meta_service.cc
- src/server/meta_service.h
- src/store/heartbeat.cc
[fix][index] Fix VectorScanQuery range validate.
[feat][coordinator] Add async delete table/index.
> [fix][index] Fix VectorScanQuery range validate.

- conf/index-gflags.conf
- conf/index.template.yaml
- conf/store-gflags.conf
- src/server/cluster_service.cc
- src/server/main.cc
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_ivf_flat.cc
[fix][common] Fix omp drain threads.
[feat][index] Use faiss's pre-filter for flat index.
> [fix][common] Fix omp drain threads.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/AutoIncrement.java
https://bugs.openjdk.java.net/browse/JDK-8062841
> [fix][sdk] revert computeIfAbsent for jdk related bug

- conf/index.template.yaml
- conf/store.template.yaml
- src/scan/scan.cc
- src/scan/scan.h
- test/test_raft_snapshot_handler.cc
- test/test_region_controller.cc
- test/test_scan.cc
[fix][store] Fix Scan Open failed by wrong state.
> [fix][store] Fix Scan Open failed by wrong state.

- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/meta_service.cc
- src/store/heartbeat.cc
[fix][coordinator] Fix clean deleted table/index failed while the deleted items are numerous.
> [fix][coordinator] Fix clean deleted table/index failed while the

- proto/meta.proto
- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_meta.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
- src/server/meta_service.cc
- src/server/meta_service.h
[feat][coordinator] Implement UpdateTables, AddIndexOnTable and DropIndexOnTable.
> [feat][coordinator] Implement UpdateTables, AddIndexOnTable and

- proto/common.proto
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/coordinator_control_meta.cc
- src/engine/raw_rocks_engine.cc
- src/handler/raft_apply_handler.cc
- src/handler/raft_apply_handler_txn.cc
- src/handler/raft_snapshot_handler.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/metrics/store_metrics_manager.cc
- src/server/cluster_service.cc
- src/server/coordinator_service.cc
- src/server/index_service.cc
- src/server/service_helper.cc
- src/server/store_service.cc
- src/store/region_controller.cc
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_manager.cc
[fix] Fix vector index double free core dump
> [fix] Fix vector index double free core dump

- conf/index-gflags.conf
- src/coordinator/coordinator_control_meta.cc
- src/server/main.cc
- src/vector/vector_index_hnsw.cc
[fix][coordinator] Fix DropTable/DropIndex failed to erase id from schema.
> [fix][coordinator] Fix DropTable/DropIndex failed to erase id from schema.

- conf/coordinator.template.yaml
- proto/coordinator.proto
- proto/index.proto
- proto/store.proto
- src/client/coordinator_client_function_watch.cc
- src/coordinator/auto_increment_control.h
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/kv_control.h
- src/coordinator/kv_control_fsm.cc
- src/coordinator/kv_control_watch.cc
- src/coordinator/tso_control.cc
- src/coordinator/tso_control.h
- src/metrics/store_metrics_manager.h
- src/server/coordinator_service.cc
- src/server/coordinator_service.h
- src/server/index_service.cc
- src/server/index_service.h
- src/server/main.cc
- src/server/meta_service.cc
- src/server/meta_service.h
- src/server/service_helper.h
- src/server/store_service.cc
- src/server/store_service.h
- src/server/version_service.cc
- src/server/version_service.h
Add WorkerSet for coordinator to cope with multi thread rpc call to lock.
Add Hello rpc to store and index for monitor system.
> [fix] Add WorkerSet for coordinator

- src/client/coordinator_client_function.h
- src/client/coordinator_client_function_coor.cc
- src/client/dingodb_client.cc
- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_coor.cc
- src/coordinator/kv_control_kv.cc
- src/server/coordinator_service.cc
- src/server/version_service.cc
Fix KvRange count-only=true.
Add CreateRegion to dingodb_client.
> [fix][coordinator] Fix ScanRegion end_key bug.

- proto/common.proto
- src/client/coordinator_client_function_meta.cc
- src/client/dingodb_client.cc
- src/common/constant.h
- src/coordinator/coordinator_control_meta.cc
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_factory.cc
- src/vector/vector_index_factory.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- src/vector/vector_index_ivf_flat.h
- src/vector/vector_index_ivf_pq.cc
- src/vector/vector_index_ivf_pq.h
- src/vector/vector_index_raw_ivf_pq.cc
- src/vector/vector_index_raw_ivf_pq.h
- src/vector/vector_reader.cc
- src/vector/vector_reader.h
- test/test_vector_index_flat.cc
- test/test_vector_index_ivf_pq.cc
- test/test_vector_index_raw_ivf_pq.cc
- test/test_vector_index_raw_ivf_pq_boundary.cc
[feat][index] Add ivf pq vector index.
> [feat][index] Add ivf pq vector index.

- proto/index.proto
- proto/store.proto
- src/client/dingodb_client.cc
- src/client/store_client_function.h
- src/client/store_client_function_txn.cc
- src/common/helper.cc
- src/coordinator/kv_control.h
- src/coordinator/kv_control_fsm.cc
- src/coordinator/kv_control_kv.cc
- src/engine/engine.h
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/engine/txn_engine_helper.cc
- src/engine/txn_engine_helper.h
- src/server/index_service.cc
- src/server/index_service.h
- src/server/server.h
- src/server/store_service.cc
- src/server/store_service.h
- src/server/util_service.cc
[fix][coordinator] Fix possible KvPut with obsolete lease_id.
> [fix][coordinator] Fix possible KvPut with obsolete lease_id

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/DingoClientException.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/ServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/lock/LockService.java
Fix service connector generate err exception bring many retry
> [fix][sdk] Fix service connector generate err exception bring many retry

- src/vector/vector_index.cc
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_ivf_flat.cc
- src/vector/vector_index_ivf_flat.h
- src/vector/vector_index_ivf_pq.cc
- src/vector/vector_index_ivf_pq.h
- src/vector/vector_index_raw_ivf_pq.cc
- src/vector/vector_index_raw_ivf_pq.h
- test/test_vector_index_ivf_flat.cc
- test/test_vector_index_ivf_pq.cc
- test/test_vector_index_raw_ivf_pq.cc
[fix][index] Fix ivf_flat search bug.
> [fix][index] Fix ivf_flat search bug.

- CMakeLists.txt
- src/example/CMakeLists.txt
- src/example/meta_cache_example.cc
- src/sdk/CMakeLists.txt
- src/sdk/meta_cache.cc
- src/sdk/meta_cache.h
- src/sdk/status.cc
- src/sdk/status.h
- test/CMakeLists.txt
- test/sdk/CMakeLists.txt
- test/sdk/test_meta_cache.cc
- test/sdk/test_meta_cache.h
> [feat][sdk] Implement MetaCache

- src/vector/vector_index_ivf_flat.cc
- src/vector/vector_index_ivf_pq.cc
- src/vector/vector_index_raw_ivf_pq.cc
[fix][index] Fix ivf_flat and ivf_pq search if no data sdk handle error bug.
> [fix][index] Fix ivf_flat and ivf_pq search if no data sdk handle error bug.

- proto/error.proto
- src/common/helper.cc
- src/common/helper.h
- src/common/synchronization.h
- src/engine/iterator.h
- src/engine/raw_bdb_engine.cc
- src/engine/raw_bdb_engine.h
- src/engine/raw_rocks_engine.cc
- src/engine/raw_rocks_engine.h
- test/test_bdb_engine.cc
[store] implement raw bdb engine.
> [store] implement raw bdb engine.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/Coordinator.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/InternalCoordinator.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/InternalRegion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/InternalStore.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/Region.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/Store.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/cluster/ClusterServiceClient.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
> [wip][fix][dingo-sdk] Add monitor interface

- proto/common.proto
- src/client/dingodb_client.cc
- src/client/store_client_function.cc
- src/client/store_client_function.h
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
- src/vector/vector_index_hnsw.cc
- src/vector/vector_index_hnsw.h
- src/vector/vector_index_ivf_flat.cc
- src/vector/vector_index_ivf_flat.h
- src/vector/vector_index_ivf_pq.cc
- src/vector/vector_index_ivf_pq.h
- src/vector/vector_index_raw_ivf_pq.cc
- src/vector/vector_index_raw_ivf_pq.h
- src/vector/vector_index_utils.cc
- src/vector/vector_index_utils.h
- src/vector/vector_reader.cc
- src/vector/vector_reader.h
- test/test_raft_node.cc
- test/test_vector_index_flat.cc
- test/test_vector_index_ivf_flat.cc
- test/test_vector_index_ivf_pq.cc
- test/test_vector_index_raw_ivf_pq.cc
- test/test_vector_index_raw_ivf_pq_boundary.cc
[feat][index] Add range search API Interface.
> [feat][index] Add range search API Interface.

- src/coordinator/coordinator_control_meta.cc
[fix][index] Add create ivf pq param check in coordinator.
> [fix][index] Add create ivf pq param check in coordinator.

- src/engine/raw_bdb_engine.cc
- src/engine/raw_bdb_engine.h
- test/test_bdb_engine.cc
[feat][store] Raw bdb engine, implement remained functions.
> [feat][store] Raw bdb engine, implement remained functions.

- src/vector/vector_index_snapshot_manager.cc
[fix][index] Fix ivf_flat and ivf_pq save error.
> [fix][index] Fix ivf_flat and ivf_pq save error.

- src/coordinator/kv_control_kv.cc
We must do PutKvRev before PutKvIndex, because if kv_index is updated, client can catch sight of kv_rev that is not write yet.
When doing delete and compact, the sequence is contrary, we must do PutKvIndex before PutKvRev.
> [fix][coordinator] Fix KvPut concurrent can not find kv rev bug.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/InternalRegion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/Region.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/cluster/ClusterServiceClient.java
Add region followers for monitor
> [fix][dingo-sdk] Add region followers for monitor

- conf/index.template.yaml
- conf/store.template.yaml
- src/common/helper.cc
- src/common/helper.h
- src/engine/raw_engine.h
- src/handler/raft_snapshot_handler.cc
- src/server/index_service.cc
- src/server/index_service.h
- src/server/main.cc
- src/server/store_service.cc
- src/server/store_service.h
- src/server/util_service.cc
- src/server/util_service.h
- src/store/region_controller.cc
- test/test_split_checker.cc
[refactor] Add read and write worker set for store and index service.
> [refactor] Add read and write worker set for store and index service.

- test/test_vector_index_raw_ivf_pq_boundary.cc
[test][index] Tidy ivf pq boundary test.
> [test][index] Tidy ivf pq boundary test.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/Column.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/ColumnDefinition.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/Table.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/TableDefinition.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- proto/meta.proto
Add attributes to table: comment, charset, collate
Add attributes to table: comment, state
> [fix][dingo-sdk] Add table or col comment

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/ColumnDefinition.java
Add comment setter for mysql meta init
> [fix][dingo-sdk] Add comment setter for mysql meta init

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- proto/meta.proto
Resolve comment null PointerException
> [fix][dingo-sdk] Resolve comment null PointerException

- src/engine/storage.cc
- src/metrics/store_metrics_manager.cc
[fix][store] Fix coredump for NewVectorReader when region is just deleted.
> [fix][store] Fix coredump for NewVectorReader when region is just

- proto/common.proto
- proto/coordinator.proto
- proto/debug.proto
- proto/file_service.proto
- proto/index.proto
- proto/meta.proto
- proto/node.proto
- proto/push.proto
- proto/raft.proto
- proto/store.proto
- proto/version.proto
- src/client/coordinator_client_function_meta.cc
- src/common/context.h
- src/common/helper.cc
- src/common/helper.h
- src/server/coordinator_service.cc
- src/server/index_service.cc
- src/server/meta_service.cc
- src/server/node_service.cc
- src/server/service_helper.cc
- src/server/service_helper.h
- src/server/store_service.cc
- src/server/version_service.cc
[feat][common] Add request and response info for all request and response.
> [feat][common] Add request and response info for all request and

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/InternalRegion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/cluster/Region.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/cluster/ClusterServiceClient.java
> [fix][dingo-sdk] Add leader location to region

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/RecordDecoder.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/index/IndexServiceClient.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/store/StoreServiceClient.java
[fix][sdk] Fix service client not catch execption.
> [fix][sdk] Fix service client not catch execption.

- test/test_vector_index_raw_ivf_pq_boundary.cc
[test][fix] Add ivf pq boundary test timestamp.
> [test][fix] Add ivf pq boundary test timestamp.

- src/vector/vector_index_utils.cc
[fix][index] Refactor ivf_flat and ivf_pq default param check.
> [fix][index] Refactor ivf_flat and ivf_pq default param check.

- src/vector/vector_index_utils.cc
[fix][index] Change ivf_pq nbits_per_idx to (0, 16]
> [fix][index] Change ivf_pq nbits_per_idx to (0, 16]

- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] Fix coordinator UpdateTableDefinition of generate meta_increment.
> [fix][coordinator] Fix coordinator UpdateTableDefinition of generate

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/Table.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/TableDefinition.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- proto/meta.proto
> [fix][dingo-sdk] Add table type,row format

- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/Constant.java
- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/MessageGenerateProcessor.java
- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/RpcMethodAnnotationProcessor.java
- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/SerializeGenerateProcessor.java
- java/dingo-sdk/pom.xml
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/DingoClientException.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/codec/CodecUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/grpc/serializer/SizeUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/grpc/serializer/Writer.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/AutoIncrementService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Caller.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/ChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/CoordinatorChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/RegionChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/RpcHandler.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/ServiceHandler.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Services.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/TableRegionsFailOver.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/RpcCaller.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/RpcFuture.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/RpcHandler.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/ServiceCaller.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/ServiceHandler.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/connector/ServiceConnector.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/entity/Message.java
[fix][sdk] Add request id for rpc call and fix some rpc bugs
> [fix][sdk] Add request id for rpc call and fix some rpc bugs

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/ChannelManager.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Services.java
- proto/common.proto
[fix][sdk] Set services cache size and add null location filter
> [fix][sdk] Set services cache size and add null location filter

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/Table.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/TableDefinition.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- proto/meta.proto
> [fix][dingo-sdk] Add table type,row format for 0.7.1

- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/MessageGenerateProcessor.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/RecordDecoder.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/RecordEncoder.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/ByteArrayUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/CoordinatorChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/RegionChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/ServiceHandler.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Services.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/RpcCaller.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/RpcHandler.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/ServiceCaller.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/ServiceHandler.java
- java/dingo-sdk/src/test/resources/simplelogger.properties
[fix][sdk] Fix codec txn key namespace and fix tso leader location
> [fix][sdk] Fix codec txn key namespace and fix tso leader location

- src/handler/raft_apply_handler_txn.cc
- src/handler/raft_snapshot_handler.cc
- src/server/store_service.cc
[fix][store] Remove unused range check in HandleMultiCfPutAndDeleteRequest.
> [fix][store] Remove unused range check in

- java/dingo-grpc-tools/pom.xml
- java/dingo-sdk/pom.xml
- java/pom.xml
> [fix][dingo-sdk] Modify version to 0.7.1

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/AutoIncrement.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/AutoIncrementService.java
Add update autoincrement id by table
> [fix][dingo-sdk] Add update autoincrement id by table

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/AutoIncrement.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/AutoIncrementService.java
> [fix][dingo-sdk] Modify update incrementId

- .gitignore
- conf/index.template.yaml
- conf/store.template.yaml
- src/client/coordinator_client_function_meta.cc
- src/common/constant.h
- src/engine/gc_safe_point.cc
- src/engine/gc_safe_point.h
- src/engine/txn_engine_helper.cc
- src/engine/txn_engine_helper.h
- src/example/CMakeLists.txt
- src/example/sdk_transaction_gc_example.cc
- src/example/sdk_transaction_gc_op_all_and_lock_example.cc
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- src/server/server.cc
- test/unit_test/main.cc
- test/unit_test/test_txn_gc.cc
[feat][store] Add txn gc feature.
> [feat][store] Add txn gc feature.

- test/unit_test/test_txn_gc.cc
[test][txn] Organize txn gc test code.
> [test][txn] Organize txn gc test code.

- proto/common.proto
- proto/store.proto
- src/client/store_tool_dump.cc
- src/coprocessor/utils.cc
- src/coprocessor/utils.h
- test/unit_test/test_coprocessor.cc
- test/unit_test/test_coprocessor_aggregation_manager.cc
- test/unit_test/test_coprocessor_utils.cc
- test/unit_test/test_scan_with_coprocessor.cc
[proto][store] Add coprocessor V2 proto.
> [proto][store] Add coprocessor V2 proto.

- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/Constant.java
- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/MessageGenerateProcessor.java
- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/RpcMethodAnnotationProcessor.java
- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/SerializeGenerateProcessor.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/codec/CodecUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/grpc/serializer/Reader.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/ChannelManager.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/RegionChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Services.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/TableRegionsFailOver.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/ServiceCaller.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/entity/Message.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/index/IndexServiceClient.java
[fix][sdk] Set empty message null.
> [fix][sdk] Set empty message null.

- proto/error.proto
- src/engine/storage.cc
- src/engine/txn_engine_helper.cc
- src/engine/txn_engine_helper.h
[fix][store] Fix TxnScan fail to scan data when meet prewrite pessimistic lock.
> [fix][store] Fix TxnScan fail to scan data when meet prewrite

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/AutoIncrement.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/AutoIncrementService.java
> [fix][dingo-sdk] Add update increment

- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/kv_control.cc
- src/coordinator/kv_control.h
- src/coordinator/kv_control_fsm.cc
- src/coordinator/kv_control_kv.cc
- src/coordinator/kv_control_lease.cc
- src/server/version_service.cc
[fix][coordinator] Fix cooridinator kv revision not monotonically increasing.
> [fix][coordinator] Fix cooridinator kv revision not monotonically

- src/engine/txn_engine_helper.cc
- src/server/index_service.cc
- src/server/store_service.cc
[fix] Resolve lock commit ts is 0
> [fix] Resolve lock commit ts is 0

- conf/index-gflags.conf
- conf/store-gflags.conf
- src/engine/bdb_raw_engine.cc
- src/engine/bdb_raw_engine.h
- src/raft/dingo_filesystem_adaptor.cc
[feat][store] Impelment lock_detect, checkpoint and log_archive for bdb engine.
> [feat][store] Impelment lock_detect, checkpoint and log_archive for bdb

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/entity/Message.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
[feat][sdk] Add txn min_commit_ts
> [feat][sdk] Add txn min_commit_ts

- src/vector/vector_index.h
[fix][index] Optimize index filter.
> [fix][index] Optimize index filter.

- src/engine/storage.cc
- src/vector/vector_reader.cc
[fix][store] Fix duplicate scan id crash problem.
[feat][store] Open table table switch.
> [fix][store] Fix duplicate scan id crash problem.[feat][store] Open table table switch. 

- src/coordinator/coordinator_control.h
- src/coordinator/coordinator_control_meta.cc
- src/coordinator/coordinator_meta_storage.h
- src/server/meta_service.cc
- test/unit_test/test_coordinator_meta_storage.cc
- test/unit_test/test_helper.cc
[fix][coordinator] Fix generate table with part ids not continuous in a table/index.
> [fix][coordinator] Fix generate table with part ids not continuous in a

- src/engine/txn_engine_helper.cc
[fix][store] Fix TxnGet cannot get correct value when meet rollback write record.
> [fix][store] Fix TxnGet cannot get correct value when meet rollback

- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor.h
- src/coprocessor/coprocessor_scalar.cc
- src/coprocessor/coprocessor_scalar.h
- src/coprocessor/coprocessor_v2.cc
- src/coprocessor/coprocessor_v2.h
- src/coprocessor/rel_expr_helper.h
- src/scan/scan.cc
- src/scan/scan.h
- src/scan/scan_manager.cc
- src/scan/scan_manager.h
- test/unit_test/test_coprocessor.cc
- test/unit_test/test_coprocessor_v2.cc
- test/unit_test/test_scan.cc
[feat][store] Add scan and coprocessor latency recorder.
> [feat][store] Add scan and coprocessor latency recorder.

- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor_v2.cc
[fix][store] Fix scan and coprocessor latency recorder potential
>  [fix][store] Fix scan and coprocessor latency recorder potential

- src/coprocessor/coprocessor_v2.cc
- src/coprocessor/coprocessor_v2.h
[feat][store] Statistics coprocessor v2 time_consumption .
> [feat][store] Statistics coprocessor v2 time_consumption .

- src/engine/storage.cc
[chore][store] Update scan error output.
> [chore][store] Update scan error output.

- src/engine/txn_engine_helper.cc
- src/engine/txn_engine_helper.h
- test/unit_test/test_txn_gc.cc
[feat][store] Prevent invalid gc table scan, if safe_point_ts = 0.
> [feat][store] Prevent invalid gc table scan, if safe_point_ts = 0.

- test/unit_test/test_vector_index_flat.cc
- test/unit_test/test_vector_index_recall_flat.cc
[test][index] Add flat recall test.
> [test][index] Add flat recall test.

- CMakeLists.txt
[chore][cmake] Optimize gdb for better debugging.
> [chore][cmake] Optimize gdb for better debugging.

- conf/coordinator-gflags.conf
- conf/index-gflags.conf
- conf/store-gflags.conf
- src/common/logging.h
- src/coordinator/kv_control_kv.cc
- src/coordinator/kv_control_lease.cc
- src/coordinator/kv_control_watch.cc
- src/engine/txn_engine_helper.cc
- src/handler/raft_apply_handler_txn.cc
[fix][store] Fix fatal for txn write to raft engine if raft apply failed.
> [fix][store] Fix fatal for txn write to raft engine if raft apply

- src/engine/txn_engine_helper.cc
[fix][store] Add error resp if CheckNotExists appear in pessimistic transaction.
> [fix][store] Add error resp if CheckNotExists appear in pessimistic

- src/vector/vector_reader.cc
- src/vector/vector_reader.h
[feat][index] Add Scalar Data with post filter with coprocessor.
> [feat][index] Add Scalar Data with post filter with coprocessor.

- conf/coordinator-gflags.conf
- src/coordinator/coordinator_control_meta.cc
[feat][coordinator] Add replica number configuration, default  3.
> [feat][coordinator] Add replica number configuration, default  3.

- src/vector/vector_reader.cc
[feat][index] Rollback scalar data support equal value compare with post filter.
> [feat][index] Rollback scalar data support equal value compare with post filter.

- src/engine/txn_engine_helper.cc
[feat][txn] Add txn gc flags at start and end. Help testers better locate problems.
> [feat][txn] Add txn gc flags at start and end. Help testers better locate problems.

- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_reader.cc
- test/unit_test/test_vector_index_flat.cc
- test/unit_test/test_vector_index_flat_search_limit.cc
- test/unit_test/test_vector_index_flat_search_param.cc
- test/unit_test/test_vector_index_hnsw_search_param.cc
- test/unit_test/test_vector_index_ivf_flat.cc
- test/unit_test/test_vector_index_ivf_pq.cc
- test/unit_test/test_vector_index_raw_ivf_pq.cc
- test/unit_test/test_vector_index_raw_ivf_pq_boundary.cc
[fix][index] Fix vector ivf pq in no data search failed.
> [fix][index] Fix vector ivf pq in no data search failed.

- proto/coordinator_internal.proto
- src/client/coordinator_client_function_meta.cc
- src/coordinator/coordinator_control_fsm.cc
- src/coordinator/coordinator_control_meta.cc
[fix][coordinator] Fix GetTables cannot get all indexes in some situation.
> [fix][coordinator] Fix GetTables cannot get all indexes in some

- src/vector/vector_reader.cc
[fix][index] Fix vector search for scalar pre filter bug.
> [fix][index] Fix vector search for scalar pre filter bug.

- java/dingo-sdk/pom.xml
- java/pom.xml
[dingo-release] bump release version to dingo-v0.8.0
> [dingo-release] bump release version to dingo-v0.8.0

- java/dingo-grpc-tools/pom.xml
- java/dingo-sdk/pom.xml
- java/pom.xml
[feat] Start a new version to v0.9.0
> [feat] Start a new version to v0.9.0

- proto/common.proto
[feat][proto] Add scalar data speed up key proto.
> [feat][proto] Add scalar data speed up key proto.

- scripts/format_code.sh
- src/client/coordinator_client_function_meta.cc
- src/coprocessor/aggregation.h
- src/vector/vector_index_utils.h
- test/unit_test/test_vector_index_ivf_pq.cc
- test/unit_test/test_vector_index_utils.cc
[chore][format] format vector index code. [fix][test] Fix test_vector_index_ivf_pq.cc bug. The reason is that there
are duplicate IDs.
> [chore][format] format vector index code. [fix][test] Fix test_vector_index_ivf_pq.cc bug

- src/vector/vector_index_flat.cc
- src/vector/vector_index_flat.h
[feat][index] Optimize vector index flat add and remove performance.
> [feat][index] Optimize vector index flat add and remove performance.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/caller/ServiceCaller.java
> [fix][sdk] Add error log

- src/coprocessor/coprocessor_scalar.cc
- src/vector/vector_reader.cc
[chore][log] Disable coprocessor scalar error log output.
> [chore][log] Disable coprocessor scalar error log output.

- src/metrics/store_metrics_manager.cc
[fix][store] Add on-off switch for region metrics collection of key count.
> [fix][store] Add on-off switch for region metrics collection of key

- src/coordinator/coordinator_control_fsm.cc
[fix][coordinator] Fix DropIndexOnTable to update table_index_map correctly.
> [fix][coordinator] Fix DropIndexOnTable to update table_index_map

- CMakeLists.txt
- src/simd/distances_avx.cc
- src/simd/distances_avx.h
- src/simd/distances_avx512.cc
- src/simd/distances_avx512.h
- src/simd/distances_ref.cc
- src/simd/distances_ref.h
- src/simd/distances_sse.cc
- src/simd/distances_sse.h
- src/simd/hook.cc
- src/simd/hook.h
- src/simd/instruction_set.h
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_manager.cc
- test/unit_test/legacy/vector/test_vector_index_flat_simd.cc
- test/unit_test/legacy/vector/test_vector_index_hnsw_simd.cc
[feat][index] Add simd cpu instruction set. Automatically select the CPU instruction set according to the running environment.
> [feat][index] Add simd cpu instruction set. Automatically select the CPU instruction set according to the running environment.

- .gitmodules
- CMakeLists.txt
- src/client/coordinator_client_function.h
- src/client_v2/client_helper.h
- src/client_v2/client_interation.cc
- src/client_v2/client_interation.h
- src/client_v2/client_router.cc
- src/client_v2/client_router.h
- src/client_v2/dingodb_client.cc
- src/client_v2/store_client_function.cc
- src/client_v2/store_client_function.h
- src/client_v2/store_client_function_txn.cc
- src/client_v2/store_tool_dump.cc
- src/client_v2/store_tool_dump.h
- src/client_v2/subcommand_coordinator.cc
- src/client_v2/subcommand_coordinator.h
- src/client_v2/subcommand_helper.h
- src/client_v2/subcommand_kv.cc
- src/client_v2/subcommand_lease.cc
- src/client_v2/subcommand_meta.cc
- src/client_v2/subcommand_store.cc
- src/client_v2/subcommand_tools.cc
support subcommands and help info
> [refactor][dingo-client] Refactor dingo client

- src/client_v2/subcommand_meta.cc
- src/vector/vector_index_utils.cc
[clore][proto] update proto and diskann.
> [clore][proto] update proto and diskann.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
> [fix][dingo-sdk] Add watchLock without filter

- .cmake-format.json
- CMakeLists.txt
- cmake/bdb.cmake
- cmake/braft.cmake
- cmake/brpc.cmake
- cmake/diskann.cmake
- cmake/faiss-mkl.cmake
- cmake/faiss-openblas.cmake
- cmake/fmt.cmake
- cmake/ftxui.cmake
- cmake/gflags.cmake
- cmake/glog.cmake
- cmake/gperftools.cmake
- cmake/gtest.cmake
- cmake/leveldb.cmake
- cmake/libbacktrace.cmake
- cmake/libunwind.cmake
- cmake/lz4.cmake
- cmake/nlohmann.cmake
- cmake/openblas.cmake
- cmake/openssl.cmake
- cmake/protobuf.cmake
- cmake/rapidjson.cmake
- cmake/rocksdb.cmake
- cmake/snappy.cmake
- cmake/tantivy-search.cmake
- cmake/yaml-cpp.cmake
- cmake/zlib.cmake
- cmake/zstd.cmake
- test/unit_test/CMakeLists.txt
[chore][cmake] Unified CMakeLists.txt format. line_width = 120.
> [chore][cmake] Unified CMakeLists.txt format. line_width = 120.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
> [fix][dingo-sdk] Watch key all event

- test/unit_test/common/test_serial_helper.cc
- test/unit_test/vector/test_vector_index_flat.cc
- test/unit_test/vector/test_vector_index_flat_search_limit.cc
- test/unit_test/vector/test_vector_index_flat_search_param.cc
- test/unit_test/vector/test_vector_index_hnsw.cc
- test/unit_test/vector/test_vector_index_hnsw_search_param.cc
- test/unit_test/vector/test_vector_index_ivf_flat.cc
- test/unit_test/vector/test_vector_index_recall_flat.cc
[clore][deploy] Fix gcc-13 compile bug.
> [clore][deploy] Fix gcc-13 compile bug.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
> [fix][dingo-sdk] Watch event block

- test/unit_test/vector/test_diskann_item_runtime.cc
[feat][proto] Simplify diskann interface.
> [feat][proto] Simplify diskann interface.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Services.java
> [fix][dingo-sdk] Watch support redirect leader

- src/common/constant.h
- src/common/context.h
- src/engine/gc_safe_point.cc
- src/engine/gc_safe_point.h
- src/engine/txn_engine_helper.cc
- src/engine/txn_engine_helper.h
- src/meta/store_meta_manager.cc
- src/meta/store_meta_manager.h
- test/unit_test/txn/test_gc_safe_point.cc
- test/unit_test/txn/test_mvcc_gc.cc
- test/unit_test/txn/test_mvcc_gc_store.cc
- test/unit_test/txn/test_txn_gc.cc
[feat][gc] Add multi-tenant gc, mvcc non-transaction gc, improve transaction gc.
> [feat][gc] Add multi-tenant gc, mvcc non-transaction gc, improve transaction gc.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/RegionChannelProvider.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/Services.java
Resolve problem: Region id not found
> [fix][dingo-sdk] Resolve problem: Region id not found

- src/diskann/diskann_item.cc
- src/diskann/diskann_item.h
- src/diskann/diskann_service_handle.cc
- src/diskann/diskann_service_handle.h
- src/diskann/diskann_utils.cc
- src/diskann/diskann_utils.h
- src/engine/engine.h
- src/engine/mono_store_engine.cc
- src/engine/mono_store_engine.h
- src/engine/raft_store_engine.cc
- src/engine/raft_store_engine.h
- src/engine/storage.cc
- src/engine/storage.h
- src/server/diskann_service.cc
- src/server/diskann_service.h
- src/server/index_service.cc
- src/vector/vector_index.cc
- src/vector/vector_index.h
- src/vector/vector_index_diskann.cc
- src/vector/vector_index_diskann.h
- src/vector/vector_reader.cc
- src/vector/vector_reader.h
- test/unit_test/vector/test_diskann_brpc_client.cc
- test/unit_test/vector/test_diskann_item.cc
- test/unit_test/vector/test_diskann_utils.cc
- test/unit_test/vector/test_vector_index_diskann.cc
[feat][index] Simplify diskann interface. Add no data and start set builded function.
> [feat][index] Simplify diskann interface. Add no data and start set builded function.

- src/diskann/diskann_item.cc
- src/diskann/diskann_item_runtime.cc
[fix][index] Fix diskann nodata file after builded.
> [fix][index] Fix diskann nodata file after builded.

- test/unit_test/vector/test_diskann_brpc_client.cc
[fix][index] Fix diskann test unit.
> [fix][index] Fix diskann test unit.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/ServiceCallCycles.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/util/OnlineDdlLogUtils.java
[feat][dingo-sdk] Add online ddl sql log options
> [feat][dingo-sdk] Add online ddl sql log options

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/WatchService.java
> [fix][dingo-sdk] When the renewLease rpc timeout occurs, the owner of  the distributed lock will be cancelled and re elected

- java/dingo-grpc-tools/src/main/java/io/dingodb/grpc/MessageGenerateProcessor.java
- java/dingo-sdk/pom.xml
- java/pom.xml
[fix][dingo-sdk] Fix protobuf-java has potential denial of service issue
> [fix][dingo-sdk] Fix protobuf-java has potential denial of service issue

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/LockService.java
> [fix][dingo-sdk] Reduce renewLease log output

- src/vector/vector_index.cc
- src/vector/vector_index_diskann.cc
[fix][index] Fixed the problem that DIskANN cannot be sent and destroyed when dropping table.
> [fix][index] Fixed the problem that DIskANN cannot be sent and destroyed when dropping table.

- src/engine/storage.cc
- src/vector/vector_reader.cc
[fix][index] Fixed the issue of ignoring non-existent query errors when the original vector does not exist during vector query.
> [fix][index] Fixed the issue of ignoring non-existent query errors when the original vector does not exist during vector query.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/codec/DingoKeyValueCodec.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/Table.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/table/TableDefinition.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/EntityConversion.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/MetaServiceClient.java
Add codecVersion to tableDefinition
> [feature][dingo-sdk] Add codecVersion to tableDefinition

- src/coprocessor/coprocessor.cc
- src/coprocessor/coprocessor.h
- src/coprocessor/coprocessor_v2.cc
- src/coprocessor/coprocessor_v2.h
> [feat][serial] Optimize serial.

- src/engine/storage.cc
- src/vector/vector_index_utils.cc
- src/vector/vector_index_utils.h
Reverts dingodb/dingo-store#1268
> Revert "[WIP][feat][store]Add calculate hamming distance"

- src/coprocessor/coprocessor_v2.cc
> [feat][serial] Compatible with old version.

- src/br/backup.cc
- src/br/main.cc
- src/br/utils.cc
- src/br/utils.h
[feat][store] Add backup debug information with ts timestamp.
> [feat][store] Add backup debug information with ts timestamp.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/service/meta/AutoIncrementService.java
> [fix][dingo-sdk] Resolve the issue of slow data insertion speed in self increasing tables

- src/coprocessor/coprocessor_v2.cc
- src/coprocessor/coprocessor_v2.h
[feat][coprocessor] Optimize count expr
> [feat][coprocessor] Optimize count expr

- src/coprocessor/coprocessor_v2.cc
[fix][serial] Support selection for v2 schema
> [fix][serial] Support selection for v2 schema

- src/br/restore_region_meta.cc
- test/unit_test/br/test_restore_region_meta.cc
[test][store] Test to verify that br restore can create regions(store，index, document).
> [test][store] Test to verify that br restore can create regions(store，index, document).

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/codec/CodecUtils.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/MyDecimal.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/schema/DecimalSchema.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/schema/DingoSchema.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/schema/Type.java
- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/utils/TypeSchemaMapper.java
- java/dingo-sdk/src/test/java/sdk/common/serial/CodecTest.java
Support serialization for decimal key.
> Support serialization for decimal key.

- src/diskann/diskann_item_manager.cc
- src/diskann/diskann_item_manager.h
- test/unit_test/vector/test_diskann_flat_compare.cc
[feat][index] Add diskann hook to speed up building and querying.
[fix][index] Fix diskann inner_product and cosine distance inconsistency with faiss.
> [feat][index] Add diskann hook to speed up building and querying.[fix][index] Fix diskann inner_product and cosine distance inconsistency with faiss.

- src/br/interation.h
[fix][index] Fix br backup find Not found region when replica = 1 bug .
> [fix][index] Fix br backup find Not found region when replica = 1 bug .

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/MyDecimal.java
- java/dingo-sdk/src/test/java/sdk/common/serial/CodecTest.java
[fix][sdk] Support decimal rounding to be compatible with mysql.
> [fix][sdk] Support decimal rounding to be compatible with mysql.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/schema/DecimalSchema.java
[fix][sdk] Fix issue that no data returned when decimal column with index.
> [fix][sdk] Fix issue that no data returned when decimal column with index.

- java/dingo-sdk/src/main/java/io/dingodb/sdk/common/serial/schema/DecimalSchema.java
[fix][sdk] Fix issue about decoding prefix for Decimal type as key.
> [fix][sdk] Fix issue about decoding prefix for Decimal type as key.

- src/br/backup.cc
- src/br/backup.h
- src/br/parameter.cc
- src/br/parameter.h
[feat][br] Add br backup get job list check. default true.
> [feat][br] Add br backup get job list check. default true.

- test/unit_test/txn/test_txn_scan.cc
[fix][test]Fixup unit_test errror.
> [fix][test]Fixup unit_test errror

- .gitmodules
- CMakeLists.txt
- cmake/libaio.cmake
- src/common/version.cc
[feat][store] Makes diskann independent of the system, of course it can be configured. By default it is independent.
[feat][contrib] Add libaio submodule.
> [feat][store] Makes diskann independent of the system, of course it can be configured. By default it is independent.

- src/common/version.h
[chore][store] Update dingo-store version to 3.0.0.
> [chore][store] Update dingo-store version to 3.0.0.

- CMakeLists.txt
[fix][cmake] It is suspected that compiling diskann fails at some point.
> [fix][cmake] It is suspected that compiling diskann fails at some point.

- src/br/backup_data_base.cc
- src/br/backup_meta_base.cc
- src/br/main.cc
- src/br/parameter.cc
- src/br/parameter.h
- src/br/restore_region_data.cc
- src/br/restore_region_meta.cc
- src/br/utils.cc
- src/br/utils.h
- test/unit_test/br/test_utils.cc
[feat][br] Increase the number of copies of the region backup when automatically detecting recovery, which is configurable. default -1. Automatically select the number of copies based on backup information.
[feta][br] Increase the backup region statistics time.
[feta][br] Increase the restore region statistics time.
[feat][br] Add command line help information.
> [feat][br]  Add backup and restore some issue.

- src/coordinator/coordinator_control_coor.cc
[fix][coordinator] Fixed job list bug. This bug will cause the coordinator to crash.
> [fix][coordinator] Fixed job list bug. This bug will cause the coordinator to crash.

- CMakeLists.txt
- src/coprocessor/coprocessor_v2.cc
- src/engine/txn_engine_helper.cc
[fix][store] Fix TxnScan crash bug.
> [fix][store] Fix TxnScan crash bug.

- src/vector/vector_reader.cc
[fix][index] Temporarily solve the problem of BruteForceSearch causing index node crash. A complete fix is needed later.
> [fix][index] Temporarily solve the problem of BruteForceSearch causing index node crash. A complete fix is needed later.
